Update highcharts
kiwigrid/angular2-highcharts pull request #3
Opened 2017-11-20 15:44 UTC by Norreman

2017-11-20 16:24 UTC, marcelkilian requested changes
I commented some lines and more importanly the build fails. pls fix

2017-11-20 16:27 UTC, marcelkilian commented on dist/ChartComponent.d.ts
> -    test: any;
Why did you remove it and what did it in the first place?

2017-11-20 16:37 UTC, marcelkilian commented on package.json
> +    "@types/highcharts": "^5.0.12",
Those are type descriptions for version 5.0.12. Sadly there is no update yet.

2017-11-21 08:40 UTC, Norreman commented on dist/ChartComponent.d.ts
> -    test: any;
Its in the dist folder and this is generated. I haven't delete it on my own.

2017-11-21 08:41 UTC, Norreman commented on package.json
> +    "@types/highcharts": "^5.0.12",
Yes, sadly.

2017-11-21 15:38 UTC, marcelkilian approved these changes

2017-11-21 15:38 UTC, merged